### ISSUE TITLE
Rewarded Ad no working in android

### ISSUE THREAD

**Issue by manzajaro** [admob-plus/admob-plus#226] opened 2021-02-18 17:10 UTC
Since the update to version 0.42.0 I can't get rewarded videos on android neither in develop nor in release mode.

Thanks

**Comment by ratson** [comment] 2021-02-19 16:10
Please try out `admob-plus-cordova@1.0.0-alpha.9` see if it fixes the issues.

**Comment by nfacha** [comment] 2021-02-28 16:05
Having the same issue on your proposed version @ratson

**Comment by manzajaro** [comment] 2021-03-01 15:02
+1   I have tested in alpha 10 and it does not work.

**Comment by manzajaro** [comment] 2021-03-10 15:59
@ratson I have tested in alpha 13 and it does not work.

**Comment by manzajaro** [comment] 2021-03-10 16:54
@ratson 

Hello, I have managed to find out where the error is.

https://github.com/admob-plus/admob-plus/blob/1df062ba2c372ad9e19e6ee9120f1d89a6d58435/packages/cordova/src/android/ExecuteContext.java#L98

https://github.com/admob-plus/admob-plus/blob/1df062ba2c372ad9e19e6ee9120f1d89a6d58435/packages/cordova/src/android/ExecuteContext.java#L102

This function cannot return null to setServerSideVerificationOptions, when that happens the advertisement does not work.

The solution I have taken is to put a parameter check before this line so that it does not do that if it does not exist.

https://github.com/admob-plus/admob-plus/blob/1df062ba2c372ad9e19e6ee9120f1d89a6d58435/packages/cordova/src/android/ads/Rewarded.java#L53

**Comment by ratson** [comment] 2021-03-20 17:34
@manzajaro Thank you for finding out the cause. It has been fixed in the latest release.

**Closed by ratson** 2021-03-20 17:34 UTC
