### ISSUE TITLE
Preparing your app for iOS 14+

### ISSUE THREAD

**Issue by DesignerApparelSales** [admob-plus/admob-plus#182] opened 2020-08-19 10:15 UTC
Hi, I have been using your admob-free plugins for years, thanks a lot! Anyway, Will this plugin and your admob-free plugin work for ios 14 when it release?

Apple announced a new transparency framework that requires changes to your iOS apps with the release of iOS 14. 

To help prevent a significant loss in ad revenue, you’ll need to make the following changes prior to the release of iOS 14:

Install the latest Google Mobile Ads SDK for iOS (version 7.64 or later) for AdMob or Ad Manager.

Add the AppTrackingTransparency permission to your iOS apps. This adds a pop-up iOS AppTrackingTransparency (ATT) alert that asks users to allow access to and use of identifiers like IDFA. 
Both of these steps are required for your apps to continue monetizing with personalized ads on iOS 14.

**Comment by tomitank** [comment] 2020-08-27 21:14
Hi!
Here is my solution: (tested with xCode 12 beta 5 simulator)
1.) use my plugin: (based on cordova-plugin-admob-free)
https://www.npmjs.com/package/cordova-plugin-admob-tomitank

2.) Download the latest SDK (7.64.0):
https://developers.google.com/admob/ios/download

3.) Extract and copy the "GoogleMobileAds" file to /plugins/cordova-admob-sdk/src/ios/GoogleMobileAds.framework directory

4.)
cordova platform rm ios
cordova platform add ios

5.)
cordova build ios

ENJOY! 

Drawbacks & Bugs:
- you need to call first "admob.banner.prepare()" otherwise it doesn't work (same as the original plugin)
  this call the  AppTrackingTransparency permission.

- for unknown reasons, if the user does not respond for too long, the application will freeze. if you know the solution please let me know.

Extra:
my plugin return the AppTrackingTransparency status integer as string. so you can write extra notification for user.

Here is the possible values: https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus
authorized: 3
denied: 2

usage:
admob.banner.prepare().then(function(result) {
    alert(status);
});

**Comment by boengli** [comment] 2020-08-28 07:19
**cordova-admob-plus** has the following definition in plugin.xml:
`<framework src="Google-Mobile-Ads-SDK" type="podspec" spec="~> 7.57" />`

So a simple pod update will update the SDK:
`Installing Google-Mobile-Ads-SDK 7.64.0 (was 7.62.0)`

**Comment by tomitank** [comment] 2020-08-28 08:36
@boengli 
Ok, but but that's only half the job.
You need to rewrite the swift code as well to "AppTrackingTransparency"

**Comment by boengli** [comment] 2020-08-28 09:18
@tomitank
It was such a fiddle to get this to work and now change plugin again and rewrite everything. 
But this looks like the most reasonable decision, so I will try your plugin. praise @tomitank.

**Comment by lopezasin** [comment] 2020-08-28 13:58
> (tested with xCode 12 beta 5 simulator)
> 1.) use my plugin: (based o

Hi @tomitank . Thanks for modify the plugin, but I have a question.. Why your plugin is based in admob-free and not in admob-plus? Ratson says: "AdMob Plus is the successor of cordova-plugin-admob-free, which provides a cleaner API and build with modern tools"

**Comment by lopezasin** [comment] 2020-08-28 14:00
> Hi!
> Here is my solution: (tested with xCode 12 beta 5 simulator)
> 1.) use my plugin: (based on cordova-plugin-admob-free)
> https://www.npmjs.com/package/cordova-plugin-admob-tomitank
> 
> 2.) Download the latest SDK (7.64.0):
> https://developers.google.com/admob/ios/download
> 
> 3.) Extract and copy the "GoogleMobileAds" file to /plugins/cordova-admob-sdk/src/ios/GoogleMobileAds.framework directory
> 
> 4.)
> 
> ```
> cordova platform rm ios
> cordova platform add ios
> ```
> 
> 5.)
> `cordova build ios`
> 
> ENJOY!
> 
> Drawbacks & Bugs:
> 
> * you need to call first "admob.banner.prepare()" otherwise it doesn't work (same as the original plugin)
>   this call the  AppTrackingTransparency permission.
> * for unknown reasons, if the user does not respond for too long, the application will freeze. if you know the solution please let me know.
> 
> Extra:
> my plugin return the AppTrackingTransparency status integer as string. so you can write extra notification for user.
> 
> Here is the possible values: https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus
> authorized: 3
> denied: 2
> 
> usage:
> 
> ```
> admob.banner.prepare().then(function(result) {
>     alert(status);
> });
> ```

Hi @tomitank . Thanks for modify the plugin, but I have a question.. Why your plugin is based in admob-free and not in admob-plus? Ratson says: "AdMob Plus is the successor of cordova-plugin-admob-free, which provides a cleaner API and build with modern tools"

**Comment by unstableair** [comment] 2020-08-28 15:21
Many thanks @tomitank your fork of cordova-plugin-admob-free works for me just as documented and is a big help, kudos for publishing.

However, as far as I can tell, the only way to get the current tracking status is to call admob.banner.prepare() but calling prepare will cause the apple tracking request dialog to be shown to the user. This means I can't provide extra notification to the user based on the status returned from prepare as they have already been shown the tracking request by the time the status is available to me.

For me it would be much better if there were 2 new calls added, one to return the current tacking status (without making the request to the user) and another one to request the app tracking authorisation.

It looks like we only get one shot at getting the user to allow tracking so it's really important to let them know why we track before the authorisation request dialog is shown.

**Comment by tomitank** [comment] 2020-08-28 18:49
@lopezasin 
i tried the admob-plus too, but it's was buggy. eg: banner hide function not worked for me. I don't know swift language & i have less time for find the issue, especially for especially a lot of bugs.

----------------------------------
@unstableair 
it's very easy:
you can use the cordova notification before you call the banner.prepare function.
something like:
```
navigator.notification.confirm(msg, function() {
    call admob banner code here..
}, title, buttons);
```

and dont forget the NSUserTrackingUsageDescription in info.plist
```
<key>NSUserTrackingUsageDescription</key>
<string>This identifier will be used to deliver personalized ads to you.</string>
```

**Comment by kieranmcdev** [comment] 2020-08-29 08:32
Thanks very much for the fork @tomitank, I will be giving this a go over the next couple of days.

Currently in my app, I have popups for gdpr and ad personalisation to set the npa flag correctly. Am I correct in thinking that this is an additional consent popup needed by the user? Just thinking that a new user will be met with 3 popups in a row and is very likely to just leave the app....

**Comment by unstableair** [comment] 2020-08-29 09:53
Thanks for the update @tomitank 
The problem is that if I display the extra notification *before* I call the new banner.prepare then the extra info will be displayed every time the app is started even if the  user has already set the tracking preference.

The logic needs to be:

1. Get trackingAuthorizationStatus

2. IF trackingAuthorizationStatus set to 'notDetermined' 
        2.1 Show my extra information dialog
        2.2 Call requestTrackingAuthorization

3. Call banner.prepare etc. etc.

If trackingAuthorizationStatus is set to anything other than 'notDetermined' then the user has already set the tracking authorisation.

The most flexible way would be if the trackingAuthorizationStatus value and requestTrackingAuthorization call were exposed to cordova as new function calls rather than having them baked into the banner.prepare call.

I've tried to write a new cordova plugin just to expose the iOS 14 Ad Tracking calls but I don't have the Objective C skills to get it working :(

**Comment by tomitank** [comment] 2020-08-29 14:15
New version is available:

new version use my cordova-admob-sdk-tomitank plugin.

No more need make this steps: 2, 3,  and 4.

Simple use the cordova-plugin-admob-tomitank plugin!

---------------------------

@kieranmcdev 
do you thinking about navigator.notification.confirm?
No it's not needed.
And if you don't care about the choice then use simple this: admob.banner.prepare();

---------------------------

@unstableair 
`I don't have the Objective C skills `
unfortunately I don't either, but maybe later i try to write to your logic.
Only need to add a new function, which is check the status..

**Comment by kieranmcdev** [comment] 2020-08-29 14:42
My question is possibly more of a legal one but just wondering if someone had the answer!

I set the personalised ads flag (npa) based on a consent popup asking the user if they will allow personalised ads. Is this still needed as well as the App Tracking dialog that will appear?

**Comment by tomitank** [comment] 2020-08-29 14:53
@kieranmcdev 
Yes. This is the right way:
https://support.google.com/admob/answer/9997589?hl=en

(But if you can set the appropriate variables through a native application, it is possible that it is also accepted.)

**Comment by tomitank** [comment] 2020-08-29 22:56
New version is available:
------------------------

Added 2 function instead of banner.prepare()

Usage:
-------------------------------------------------------
```
admob.getTrackingStatus().then(function(result) {
    alert(status);
});

admob.trackingStatusForm().then(function(result) {
    alert(status);
    // load + show ads..
    // admob.banner.prepare();
    // etc..
});
```

**Comment by tomitank** [comment] 2020-08-30 18:57
New (stable) version is available:
------------------------------------
New functions working on Android as well. return "authorized" is every case.

Update is recommended!

Usage:
-------------------------------------------------------
```
admob.getTrackingStatus().then(function(result) {

    alert(status);

    admob.trackingStatusForm().then(function(result) {
        alert(status);
        // load + show ads..
        // admob.banner.prepare();
        // etc..
    });
});
```

- all others functions same as in https://github.com/ratson/cordova-plugin-admob-free

Result:
-------------------------------------------------------
This plugin return the AppTrackingTransparency status name. So you can write extra notification for user.
Info: https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus

Support:
-------------------------------------------------------
If you want to support please write here: tanky.hu@gmail.com

ENJOY!

**Comment by jonatarussi** [comment] 2020-08-31 12:57
Hi @tomitank thanks for your plugin. When I try to compile I receive this error: 'AppTrackingTransparency/AppTrackingTransparency.h' file not found

Do you know why this error? I think that is because I do not have iOS SDK 14

**Comment by jonatarussi** [comment] 2020-08-31 19:14
HI @tomitank thanks for your plugin.
When I try to compile I always get this error: cordova-plugin-admob-tomitank/CDVAdMob.h:14:9: fatal error: 'AppTrackingTransparency/AppTrackingTransparency.h' file not found

Do you know why?

**Comment by tomitank** [comment] 2020-08-31 19:27
@jonatarussi 
Hi!
Did you use Xcode 12 beta 5 or above?

**Comment by jonatarussi** [comment] 2020-08-31 19:30
@tomitank 
Yes, I am using. But this error occurs when I try to compile using cordova.. 'cordova compile ios'

**Comment by tomitank** [comment] 2020-08-31 19:40
I never use cordova compile.
try just: cordova build ios

**Comment by jonatarussi** [comment] 2020-08-31 19:42
Sorry... it is cordova build ios... I typed wrong..

I am using cordova 8.1.0 and cordova-ios 5.1.1

**Comment by tomitank** [comment] 2020-08-31 19:44
> I am using cordova 8.1.0 and cordova-ios 5.1.1

I think it's a problem. 
Tracking and Xcode 12 work only with latest cordova for me. (cordova-ios 6.1.0)

**Comment by tomitank** [comment] 2020-08-31 19:50
And please check that you have cordova-admob-sdk-tomitank folder in the plugins folder after cordova add ios is successed.

**Comment by jonatarussi** [comment] 2020-08-31 19:52
Thanks, I will update to cordova-ios 6.1.0
And yes, the cordova-admob-sdk-tomitank folder is in the plugins folder

Thanks again

**Comment by tomitank** [comment] 2020-08-31 19:54
With pleasure!
Happy coding!

**Comment by tomitank** [comment] 2020-08-31 19:56
And don't forget to read from cordova-ios 6
You don't need Wkwebview plugin, splashscreen plugin, file plugin to read local files etc..

**Comment by jonatarussi** [comment] 2020-08-31 19:58
I will read. Thanks for the tips!

**Comment by dcarvajal7** [comment] 2020-09-03 09:47
> ## New (stable) version is available:
> New functions working on Android as well. return "authorized" is every case.
> 
> Update is recommended!
> 
> https://www.npmjs.com/package/cordova-plugin-admob-tomitank
> 
> ## Usage:
> ```
> admob.getTrackingStatus().then(function(result) {
> 
>     alert(status);
> 
>     admob.trackingStatusForm().then(function(result) {
>         alert(status);
>         // load + show ads..
>         // admob.banner.prepare();
>         // etc..
>     });
> });
> ```
> 
> * all others functions same as in https://github.com/ratson/cordova-plugin-admob-free
> 
> ## Result:
> This plugin return the AppTrackingTransparency status name. So you can write extra notification for user.
> Info: https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/authorizationstatus
> 
> ## Support:
> If you want to support please write here: [tanky.hu@gmail.com](mailto:tanky.hu@gmail.com)
> 
> ENJOY!

Hello, admob plus already has a consent plugin, is it valid for ios 14?

I am considering migrating to admob plus from admob free for this. But I don't know if the consent plugin is the one that activates  "AppTrackingTransparency".

If so, what is the point of your plugin? to continue using admob free right?

Thanks!

**Comment by tomitank** [comment] 2020-09-03 15:19
> I am considering migrating to admob plus from admob free for this. But I don't know if the consent plugin is the one that activates "AppTrackingTransparency".

Unfortunately not.

**Comment by lopezasin** [comment] 2020-09-04 14:47
@tomitank Do you know why dont fire the events using Capacitor? I migrated from Cordova and I havent problem with other plugins. Thanks!

**Comment by tomitank** [comment] 2020-09-04 15:02
@lopezasin 
Unfortunately don't support capacitor directly.
but - after i read this - i don't no why not working:
https://capacitorjs.com/docs/cordova/using-cordova-plugins

**Comment by tomitank** [comment] 2020-09-04 15:24
@lopezasin 

> Does not fail, but events are not triggered 

please write here you admob (JavaScript) code.

**Comment by lopezasin** [comment] 2020-09-04 16:21
1. At first I create listeners

document.addEventListener('admob.interstitial.CLOSE', function() {
	
		alert("CLOSE")
  
})


document.addEventListener('admob.interstitial.OPEN', function() { //Este método solo existe en el plugin de iOS14
	alert("OPEN")
 $('.hover_bkgr_fricc').hide()
 BloquearBotones=false;
 
})

document.addEventListener('admob.interstitial.LOAD_FAIL', function() {
 		alert("LOAD_FAIL")
  })

After...

				alert("PREPARE")
				admob.interstitial.config({
				 id: AnuncioIntersticialGlobalIOS
				})

				admob.interstitial.prepare()


At last..

alert("SHOW")
admob.interstitial.show()

I get 2 alert messages: PREPARE and SHOW

**Comment by unstableair** [comment] 2020-09-07 11:36
FYI - Apple has delayed the requirement to request tracking until 2021.

"To give developers time to make necessary changes, apps will be required to obtain permission to track users starting early next year."

https://developer.apple.com/news/?id=hx9s63c5

**Comment by DesignerApparelSales** [comment] 2020-09-07 13:27
Do we still need to " Install the latest Google Mobile Ads SDK for iOS (version 7.64 or later) for AdMob or Ad Manager." till 2021?

**Comment by DesignerApparelSales** [comment] 2020-09-07 13:28
> FYI - Apple has delayed the requirement to request tracking until 2021.
> 
> "To give developers time to make necessary changes, apps will be required to obtain permission to track users starting early next year."
> 
> https://developer.apple.com/news/?id=hx9s63c5

Do we still need to " Install the latest Google Mobile Ads SDK for iOS (version 7.64 or later) for AdMob or Ad Manager." till 2021?

**Comment by tomitank** [comment] 2020-09-07 21:06
**Please update cordova-plugin-admob-tomitank! (with admob-sdk-tomitank plugin)**
This use the latest iOS SDK (7.65.0). in 7.64.0 the Interstitial and reward ads was not full screen..
Probably the last update I'll announce here.
It's ready for iOS 14!

**Comment by jellomaster** [comment] 2020-09-10 17:43
It would probably be better to just implement Googles UMP Sdk with Funding Choices... that way you're not only handling ATT for ios 14 but also the EU GDPR with the same SDK.  That way Google will display a popup explaining the Apple ATT dialog before displaying it.    See: https://developers.google.com/admob/ump/ios/quick-start

**Comment by tomitank** [comment] 2020-09-10 18:57
@jellomaster 
yes, i written this above..
Unfortunately, I don't have time for that now. maybe later.
If someone implement this SDK please let me know.

**Comment by jellomaster** [comment] 2020-09-11 19:38
I created a UMP plugin for IOS only as of now:
cordova-plugin-google-ump

It somewhat works ... if you are in EEA it will display the GDPR messages you setup in Funding Choices.  Doesn't display the ATT or  IDFA explainer messages yet.
This seems to be a bug and Google is working on it.

https://github.com/jellomaster/cordova-plugin-google-ump

**Comment by DesignerApparelSales** [comment] 2020-09-12 09:10
Hi Tomitank, thanks for your plugin. I normal use adobe phone build to build my app, when I use <plugin name="cordova-plugin-admob-tomitank" version="2.2.7" source="npm" /> inside config.xml it give me an error "Error - One of your plugins requires a parameter: ADMOB_APP_ID - You can fix this here", Do I have to use your plugin with local build only?

**Comment by tomitank** [comment] 2020-09-12 14:18
@DesignerApparelSales 
Hi!
the new features work only with xCode 12, but it's in beta state, so you can testing only with emulator, bacause of the App Store Connect does not support apps that build with beta software.
So we need to wait for xCode release..

**Comment by tomitank** [comment] 2020-09-12 15:12
Oh and don't forget:
```
	<plugin name="cordova-plugin-admob-tomitank" source="npm" spec="*">
		<variable name="ADMOB_APP_ID" value="ca-app-pub-xxxxxxxxxxxxxxxxx" />
	</plugin>
```

**Comment by DesignerApparelSales** [comment] 2020-09-12 15:22
Thanks, I'll give it a try tomrrow :)

**Comment by DesignerApparelSales** [comment] 2020-09-14 17:24
> Oh and don't forget:
> 
> ```
> 	<plugin name="cordova-plugin-admob-tomitank" source="npm" spec="*">
> 		<variable name="ADMOB_APP_ID" value="ca-app-pub-xxxxxxxxxxxxxxxxx" />
> 	</plugin>
> ```

I have tried for a couples of days to get the local build working on a virtualbox with macOS in it. its keep getting error because of the cocoapods don't want to install properly. Anyway, I have give up on that and switch to voltbuilder , its said it will build like phonegap build with all the phonegap plugins, So I'll give that a try and will see if your plugin work. thanks again.

**Comment by dcarvajal7** [comment] 2020-09-20 18:25
> **Please update cordova-plugin-admob-tomitank! (with admob-sdk-tomitank plugin)**
> This use the latest iOS SDK (7.65.0). in 7.64.0 the Interstitial and reward ads was not full screen..
> Probably the last update I'll announce here.
> It's ready for iOS 14!

I am using '@ ionic-native / admob-free' to work with admob free, how could I access the new services of your plugin? I imagine instantiating the admob variable of your plugin directly, right? What would be the correct way? 

Thanks!!!

**Comment by tomitank** [comment] 2020-09-22 15:21
Hi!
I added to plugin the Founding Choice (User Messaging Platform SDK) for iOS.
Currently i not recommended to use, because it's buggy. The error is inside the SDK. If the user tap the "I’ll decide later" button and restart the app, the Google not send the form again. So I didn't spend time with the android version.
The new version already uses cocoapods. So you need to open the APPNAME.xcworksplace instead of APPNAME.xcodeproj.

https://www.npmjs.com/package/cordova-plugin-admob-tomitank

**Comment by rastafan** [comment] 2020-09-24 13:19
Using a new plugin right now might be a problem. 
I would like to ask @ratson if he plan to release this iOS14 adaptation directly on admob-plus .
Thanks anyway to @tomitank and everyone for the informations and testing.

**Comment by tomitank** [comment] 2020-09-24 13:31
@rastafan 
> Using a new plugin right now might be a problem.

Yes it's true. So i keep the simple way in the plugin too. If you want, please use this one.
For more info, please read the README of admob-tomitank.

**Comment by rastafan** [comment] 2020-09-24 15:02
Does your plugin work when "activity tracking request" is disabled in the device settings?
Beacuse admob-plus does not seem to show any ad.

**Comment by rastafan** [comment] 2020-09-24 15:23
i'm sorry, the real english name for the setting is "allow apps to request to track" under settings->privacy->tracking .

**Comment by tomitank** [comment] 2020-09-24 15:35
> Does your plugin work when "activity tracking request" is disabled in the device settings?
@rastafan 

Yes! Only it will show non-personalized ads. IOS solves this in the background. less money..

**Comment by tomitank** [comment] 2020-09-24 15:38
I personally display a small incentive message (with help) every time app start (if the user don't authorized). Maybe the user change his mind.

**Comment by rastafan** [comment] 2020-09-24 15:39
@tomitank thank you. I opened an issue (#193) in admob-plus just to let @ratson know what is going on.
We'll try to use your plugin then, and see if we can solve our issue.
Thank you very much, and sorry everyone for spamming.

**Comment by DesignerApparelSales** [comment] 2020-09-26 19:32
Hi tomitank, 

I use Voltbuilder to build my app with your plugin. I didn't change any of my code. The build passed and the app is installed in my iphone x for testing. When I clicked to open my app, its open and immediately close the app. I reinstall my app with admob-free plugin, and its work fine. Do I need to change any code from admob-free for your plugin to work?

**Comment by tomitank** [comment] 2020-09-26 20:32
@DesignerApparelSales 
Please read this:
https://www.npmjs.com/package/cordova-plugin-admob-tomitank
+ important info:
The new version already uses cocoapods. So you need to open the APPNAME.xcworksplace instead of APPNAME.xcodepro

I don't know how Voltbuilder work, but i think that cocoapods it's not problem. 
First try without any admob code in your javascript code. (only install the plugin).
Then add the codes one after another. (always test!)

Maybe try the cordova-plugin-admob-tomitank version 2.2.7 (this is the last version without UMP and without cocoapods)

**Comment by matrixreal** [comment] 2020-12-08 16:58
i think it's safe to call the trackingAuthorizationStatus only in the ios 14 and don't in lower ios version overthwise the app will crash 
we can window.cordova.platformVersion or cordova device plugin to and do something like that :

**var deviceVersion = device.version;
if deviceVersion > or = "14"
// call the trackingAuthorizationStatus and admob.banner.prepare();
else
// just admob.banner.prepare();**

What do you think guys?

**Comment by tomitank** [comment] 2020-12-08 17:40
@matrixreal 
This is already checked in the plugin.
https://github.com/tomitank/cordova-plugin-admob-tomitank/blob/e9bb9a6b7a11c0134f0ce9f127cdf708d2ddc83e/src/ios/CDVAdMob.m#L132

**Comment by matrixreal** [comment] 2020-12-08 20:20
> @matrixreal
> This is already checked in the plugin.
> https://github.com/tomitank/cordova-plugin-admob-tomitank/blob/e9bb9a6b7a11c0134f0ce9f127cdf708d2ddc83e/src/ios/CDVAdMob.m#L132

ok
i got black screen using this
`admob.interstitial.config({ id: admobid.interstitial, isTesting: false, autoShow: false });

			admob.banner.config({ id: admobid.banner, overlap: true, isTesting: false, autoShow: true });

			admob.getTrackingStatus().then(function(status) {

				if (status == 'notDetermined') {

					navigator.notification.confirm(LANGUAGE.tracking_info_msg, function() {

						admob.trackingStatusForm().then(function(status) {

							admob.banner.prepare(); // autoShow..

							admob.interstitial.prepare().then(function() {
								admob.interstitial.show();
							});
						});

					}, LANGUAGE.tracking_info, [LANGUAGE.okay]);

				} else {

					admob.banner.prepare(); // autoShow..

					admob.interstitial.prepare().then(function() {
						admob.interstitial.show();
					});

					if (status != 'authorized') {
						notification_confirm(LANGUAGE.tracking_error, LANGUAGE.tracking_error_msg, [LANGUAGE.close], null);
					}
				}
			});`

**Comment by matrixreal** [comment] 2020-12-09 08:25
now fixed
ads working and no black screen but i don't get the popup to allow or decline the tracking transparency
any solution?
i used your simplified code

**Comment by matrixreal** [comment] 2020-12-10 09:44
@tomitank
Can you please post again your new simplified code?
the old one not work on ios 14.X
thank you

**Comment by matrixreal** [comment] 2020-12-29 14:33
got black screen when i call (simulator or real device iphone x)
admob.trackingStatusForm();
admob.banner.config({ id: 'ca-app-pub-xxxxxxxxxxx/xxxxxx', overlap: true, isTesting: false, autoShow: true });
admob.interstitial.config({ id: 'ca-app-pub-xxxxxx/xxxxxx', isTesting: false, autoShow: false });
admob.banner.prepare();
admob.interstitial.prepare();

**Comment by tomitank** [comment] 2020-12-29 17:06
> got black screen when i call (simulator or real device iphone x)
> admob.trackingStatusForm();
> admob.banner.config({ id: 'ca-app-pub-xxxxxxxxxxx/xxxxxx', overlap: true, isTesting: false, autoShow: true });
> admob.interstitial.config({ id: 'ca-app-pub-xxxxxx/xxxxxx', isTesting: false, autoShow: false });
> admob.banner.prepare();
> admob.interstitial.prepare();

try to add this to config.xml with your datas:
```
		<config-file platform="ios" target="*-Info.plist" parent="GADIsAdManagerApp">
			<true />
		</config-file>
		<config-file platform="ios" target="*-Info.plist" parent="GADApplicationIdentifier">
			<string>ca-app-pub-9....</string>
		</config-file>
		<config-file platform="ios" target="*-Info.plist" parent="NSUserTrackingUsageDescription">
			<string>This lets us show your personalized ads, which keeps Sakk app for free</string>
		</config-file>
```

**Comment by realn3rd** [comment] 2020-12-29 17:09
How can I install this version of the plugin? 


cordova plugin add cordova-admob-plus


The command always installs the version from https://github.com/admob-plus/admob-plus

**Comment by tomitank** [comment] 2020-12-29 17:55
cordova-plugin-admob-tomitank

realn3rd <notifications@github.com> ezt írta (időpont: 2020. dec. 29., K,
18:10):

**Comment by manel00** [comment] 2021-02-13 09:56
Hello, I am facing an issue with admob, anyone knows how to deal with it please? It is desperating...
```
The following build commands failed:
        CompileSwift normal x86_64 /Users/manel/Documents/ionic_projects/xstories/xstories/platforms/ios/XStories/Plugins/cordova-admob-plus/AMSRewardVideo.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by ratson** [comment] 2021-03-23 16:53
Support is added in latest release.

**Closed by ratson** 2021-03-23 16:53 UTC
