### ISSUE TITLE
The ios app(14.6) always crashes at the second banner.k = new admob.BannerAd ({----}) part. It occurs in admob-plus-cordova Ver1.18.0 or later.

### ISSUE THREAD

**Issue by moguba** [admob-plus/admob-plus#402] opened 2021-07-07 14:01 UTC
When I checked with this ios app (14.6), the above part in showBannerAd () works normally once, but if I pass it while the app is running again, the app will always be forcibly terminated.
Also, even if you try to display the Rewarded ad with showRewardedAd () after passing through showBannerAd () once, the app will be forcibly terminated at the part of rewarded.k = new admob.RewardedAd ({}) for the first time. I will.
Banner and rewarded are set to global const so that they can be entered as many times as you like and can be controlled by others.
Also, since the application will be closed the second time, I avoided new admob.BannerAd ({----}) the second time, but an error message saying that it has not been deleted appears and the advertisement is displayed. Was not done.
Probably an error appears in the swift file and it is killed. However, before admob-plus-cordova Ver1.17.0, such a forced termination did not occur at all.
A fix in the swift file since 1.18.0 is causing the problem.
I am developing an android, ios hybrid application with cordova 10.0 javascript at monaca.
No error will occur during the build. Android apps are fine.
Even if I run admob-plus, it says that there is no problem with google admob.

**Comment by ratson** [comment] 2021-07-10 06:51
@moguba Would you confirm if the issue is fixed with `admob-plus-cordova@1.20.0`?

**Comment by moguba** [comment] 2021-07-10 21:50
It will be forcibly terminated at the same location.

Thank you for the correction.
Immediately, I compiled it with the fix plug-in.
The ver display in package.json was admob-plus-cordova@1.20.0, but it is forcibly terminated at the exact same place.
For details, although a banner ad appears once, it is forcibly terminated by new admob.BannerAd ({----}) returning from another page.
After displaying the banner ad, even if the rewarded video ad is displayed on another page, it will be forcibly terminated with new admob.RewardedAd ({}).
Also, admob-plus-cordova (ver1.20.0) created in node_modules was zipped and imported and compiled as a normal plug-in.
After all, it will be forcibly terminated at the same place.
These problems have not occurred in Ver1.17.0 or lower.

**Comment by moguba** [comment] 2021-07-15 18:34
Thank you for the correction. 
With ver 1.20.1
Both banner ads and rewarded video ads are now displayed.
However, when I come back from another page, I get a warning saying ad not found: 1 and no ads.
Also, even if I return from the rewarded video ad, the app freezes and the app does not work unless I restart it.
initAppOpenAd () is not used. Still, banner ads and rewarded video ads will still be displayed.
However, it seems that func optAdOrError () works in AMBCore.swift.
Naturally, const ad seems to stop there because I haven't created it.

**Comment by moguba** [comment] 2021-07-16 19:24
With ver 1.20.1
Both banner ads and rewarded video ads are now displayed.
If you're back from a rewarded video ad, commenting out the alert display will now show the banner ad without any issues.
However, when I come back from another page, I still get a warning saying Ad not found: 1 and no banner ads.
I don't use initAppOpenAd (), but it does show banner ads and rewarded video ads.
It seems that func optAdOrError () works in AMBCore.swift only when returning from another page.

**Comment by moguba** [comment] 2021-07-17 09:11
In ver 1.20.1, if you write admob.start (). catch (alert),
Initially, the banner ad will be displayed without error. If you hide the banner ad before going to another page, go to another page, and come back,
Ad not found: 1 An error will occur and the banner ad will not be displayed. If you go to another page again and return, the banner ad will be displayed.
If you go to the rewarded video ad display without the banner ad displayed, the rewarded video ad will be displayed, but it will freeze with the performance reward.

So, if I comment out .catch (alert), the banner ad will not be displayed on the return from other pages, but the error display will disappear.
Even if I return from the rewarded video ad with a performance fee, the banner ad is not displayed, but the app is working normally.

This means that the odd number of returns from other pages will prevent the banner ad from appearing with an Ad not found: 1 error.

.catch(alert)
Launch the app → Display banner ad → Move to another page without displaying banner ad → Move to top game page from another page, cannot display banner ad due to error → Move to another page → Move to top game page to display banner ad.

Banner ad cannot be displayed due to error → Reward video ad display → Freeze on top game page.

**Comment by moguba** [comment] 2021-07-20 20:46
There is a problem with admob-plus-cordova@1.20.1.
First, you have to comment out admob.start (). Catch (alert) and use it.
Also, the problem that the banner ad is not displayed unless reloaded in each case when returning from another page has not been solved because the "Ad not found: 1" error has occurred in swift.
On the other hand, I tried to make the case classification complicated so that the banner advertisement is always displayed on the top page and not on another page.
It's too complicated to make a script that can only be used in this version.

Is it possible to display normally without the "Ad not found: 1" error when returning from another page?
Is it possible to add banner.delete (), which is released once, instead of banner.hide ()? That is easier to use. Please consider it.
(admob.remove?)

In addition, admob-plus-cordova@1.17.0 works without such problems and countermeasures. Also, the confirmed ios is 14.7.
Android apps are fine.

**Comment by moguba** [comment] 2021-07-21 21:35
In addition, when using admob-plus doctor, it became as follows.

Welcome to Monaca Terminal Console!
/****** $ npx admob-plus doctor
npx: installed 264 in 19.959s
✓(green) googleads.g.doubleclick.net
\>(red) package.json
 ×(red) cordova.plugins.admob-plus-cordova.APP_ID_IOS
         > ca-app-pub-3940256099942544~1458002511 is a test ID
↓Cordova Android dependencies [SKIPPED]
✓(green) config.xml
  ✓(green)platform[name="ios"]/preference[name="SwiftVersion"]:5.3
  ✓(green)platform[name="ios"]/preference[name="deployment-target"]:12.0
↓platforms/ios/*.xcodeproj[SKIPPED]
↓plugins/admob-plus-cordova/package.json[SKIPPED]
/****** $

**Comment by moguba** [comment] 2021-08-30 18:59
Thank you very much.
Cordova-admob-plus Ver 1.22.0 is working properly on both ios and android.

**Comment by moguba** [comment] 2021-09-26 13:19
I tested it on ios.ios is 15.0.
In Ver 1.24.0, there was no problem, but in Ver 1.25.0, the application is forcibly terminated under certain conditions.
The problem area is the rewarded video ad part.
If you close the video ad before you get paid, you will be able to successfully return to the first game screen.
If you get paid and close the video ad, the app will crash.
If you restart the game after the forced termination, you can start the game screen in the state after getting the reward.
In other words, it is an error that the app is forcibly terminated only when returning to the top page of the app after getting the reward for the rewarded video ad.

**Closed** 2022-04-16 07:25 UTC
Labels: wontfix, pkg:cordova
