### ISSUE TITLE
[Android] App crashes at start.

### ISSUE THREAD

**Issue by arzyu** [admob-plus/admob-plus#13] opened 2018-10-07 06:38 UTC
Steps to reproduce:

```bash
cordova create test-app com.test.sample
cordova platform add android
cordova run android # It's ok
cordova plugin add cordova-admob-plus --variable ADMOB_APPLICATOIN_ID=<MY_ADMOB_APPID>
cordova run android # crash
```

adb logcat messages:

```bash
adb logcat com.test.sample *:E

10-07 14:18:41.528 27114 27114 E AndroidRuntime: FATAL EXCEPTION: main
10-07 14:18:41.528 27114 27114 E AndroidRuntime: Process: com.test.sample, PID: 27114
10-07 14:18:41.528 27114 27114 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:
10-07 14:18:41.528 27114 27114 E AndroidRuntime:
10-07 14:18:41.528 27114 27114 E AndroidRuntime: ******************************************************************************
10-07 14:18:41.528 27114 27114 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
10-07 14:18:41.528 27114 27114 E AndroidRuntime: * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
10-07 14:18:41.528 27114 27114 E AndroidRuntime: * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
10-07 14:18:41.528 27114 27114 E AndroidRuntime: * follow instructions here: https://goo.gl/h17b6x.                           *
10-07 14:18:41.528 27114 27114 E AndroidRuntime: ******************************************************************************
10-07 14:18:41.528 27114 27114 E AndroidRuntime:
10-07 14:18:41.528 27114 27114 E AndroidRuntime:
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6501)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6064)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5968)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1684)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6759)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-07 14:18:41.528 27114 27114 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

As described in the instructions link https://goo.gl/fQ2neu, I need to manually add a `meta-data` to the `AndroidManifest.xml` file to resolve this error.

![wx20181007-143155](https://user-images.githubusercontent.com/1270145/46579094-cadb8500-ca3d-11e8-9934-c7eea978915b.png)

Can this be fixed?

**Comment by znegva** [comment] 2018-10-11 13:53
A quick workaround for me was to add the following to my `config.xml` inside of the `<platform name="android">` block:

```
<config-file parent="/manifest/application" target="AndroidManifest.xml">
    <meta-data 
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="ca-app-pub-3940256099942544~3347511713" />
</config-file>
```

I also had to add `xmlns:android="http://schemas.android.com/apk/res/android"` to `widget`.

I think if these changes (of course with replacing with the correct App-ID) would be added  to the plugins `plugin.xml` everything would be fine.

**Comment by arzyu** [comment] 2018-10-13 05:49
> A quick workaround for me was to add the following to my `config.xml` inside of the `<platform name="android">` block:
> 
> ```
> <config-file parent="/manifest/application" target="AndroidManifest.xml">
>     <meta-data 
>         android:name="com.google.android.gms.ads.APPLICATION_ID"
>         android:value="ca-app-pub-3940256099942544~3347511713" />
> </config-file>
> ```
> I also had to add `xmlns:android="http://schemas.android.com/apk/res/android"` to `widget`.
> 
> I think if these changes (of course with replacing with the correct App-ID) would be added to the plugins `plugin.xml` everything would be fine.

It works like a charm! Thank you, guy.

**Comment by francoisduchemin** [comment] 2018-10-21 13:51
I have the same issue. Is there any way to fix the problem directly in the plugin so that we don't have to use the workaround? That would be awesome!

**Comment by VictorHugoDotVn** [comment] 2018-10-22 15:18
When add as above, the next issue (Cordova in Mac OS):
 Command: /Users/xxx/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/fe0623d40424f3cf9f3ff07a5582a46d/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
          -o \
          /Users/xxx/Desktop/xxx/xxx/platforms/android/app/build/intermediates/res/merged/release \
          /Users/xxx/Desktop/xxx/xxx/platforms/android/app/src/main/res/xml/config.xml

 Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0

Please help

**Comment by znegva** [comment] 2018-10-23 10:05
@VictorHugoDotVn  this seems to be a problem with aapt2, see [here](https://github.com/runtrizapps/cordova-android-disable-aapt2) for a probable solution (I do not use this, as I did not ran into this problem so far!)

**Comment by VictorHugoDotVn** [comment] 2018-10-24 23:28
Thanks all. Problem solved for my case:
- I remove all the plugin, and try to run $ cordova build android, with no issue (better list all the plugin and remove one by one to test)
- I install the android service : $ cordova plugin add cordova-android-play-services-gradle-release
- I install Admob plus
- run $ cordova build android again. 
And it is Ok now.

**Comment by ratson** [comment] 2018-10-28 23:06
https://github.com/admob-plus/admob-plus/commit/7cd05a8338ed140656ef0e0a11791209ef8157be has fixed this, it is released in v0.7.0

**Closed by ratson** 2018-10-28 23:06 UTC

**Comment by souly1** [comment] 2021-09-01 10:39
> Thanks all. Problem solved for my case:
> 
> * I remove all the plugin, and try to run $ cordova build android, with no issue (better list all the plugin and remove one by one to test)
> * I install the android service : $ cordova plugin add cordova-android-play-services-gradle-release
> * I install Admob plus
> * run $ cordova build android again.
>   And it is Ok now.

Remove and re-add plugin after platforms already exist was enough for me. thanks!

**Comment by danieldanielecki** [comment] 2022-10-24 12:39
> A quick workaround for me was to add the following to my `config.xml` inside of the `<platform name="android">` block:
> 
> ```
> <config-file parent="/manifest/application" target="AndroidManifest.xml">
>     <meta-data 
>         android:name="com.google.android.gms.ads.APPLICATION_ID"
>         android:value="ca-app-pub-3940256099942544~3347511713" />
> </config-file>
> ```
> 
> I also had to add `xmlns:android="http://schemas.android.com/apk/res/android"` to `widget`.
> 
> I think if these changes (of course with replacing with the correct App-ID) would be added to the plugins `plugin.xml` everything would be fine.

It doesn't work and the issue is still the same :-/

**Comment by danieldanielecki** [comment] 2022-10-24 12:48
Okay, the problem was I've used *Add Unit* ID, not the App *ID*. I could see the error after running `adb logcat`:

```
10-24 14:42:01.022 12932 12932 E AndroidRuntime: ******************************************************************************
10-24 14:42:01.022 12932 12932 E AndroidRuntime: * Invalid application ID. Follow instructions here:                          *
10-24 14:42:01.022 12932 12932 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
10-24 14:42:01.022 12932 12932 E AndroidRuntime: * to find your app ID.                                                       *
10-24 14:42:01.022 12932 12932 E AndroidRuntime: ******************************************************************************              
```
