### ISSUE TITLE
Consent plugin not working

### ISSUE THREAD

**Issue by alexp25** [admob-plus/admob-plus#184] opened 2020-08-25 13:15 UTC
### Is this a bug report?

Yes

### Environment

```
Ionic:

   Ionic CLI                     : 5.2.6 (C:\Users\Alex\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.3.5
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 57 other plugins)

Utility:

   cordova-res : 0.6.0
   native-run  : 0.2.2

System:

   Android SDK Tools : 26.1.1 (C:\Users\Alex\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

### Steps to Reproduce

1. create ionic 4 cordova project
2. install admob-plus and consent plugins
3. use the example code provided here: https://github.com/admob-plus/admob-plus/blob/master/examples/consent/www/js/index.js#L15

### Expected Behavior

The app should open a consent window to ask for permission to use personalized ads.

### Actual Behavior

For GDPR compliance it's required to ask for consent for showing personalized ads. I have found this implementation which unfortunately did not work: https://github.com/admob-plus/admob-plus/blob/master/examples/consent/www/js/index.js#L15

The app just does nothing when it should ask for consent, and it doesn't crash either.

I attach the logcat output where it can be seen that it's a problem with the consent plugin:

```
08-25 16:00:04.027  7009  7213 W System.err: java.lang.ClassNotFoundException: cordova.plugin.consent.Consent
08-25 16:00:04.028  7009  7213 W System.err: 	at java.lang.Class.classForName(Native Method)
08-25 16:00:04.028  7009  7213 W System.err: 	at java.lang.Class.forName(Class.java:453)
08-25 16:00:04.028  7009  7213 W System.err: 	at java.lang.Class.forName(Class.java:378)
08-25 16:00:04.028  7009  7213 W System.err: 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
08-25 16:00:04.028  7009  7213 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
08-25 16:00:04.028  7009  7213 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
08-25 16:00:04.028  7009  7213 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
08-25 16:00:04.028  7009  7213 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
08-25 16:00:04.029  7009  7213 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-25 16:00:04.029  7009  7213 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:325)
08-25 16:00:04.029  7009  7213 W System.err: 	at android.os.Looper.loop(Looper.java:142)
08-25 16:00:04.029  7009  7213 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
08-25 16:00:04.029  7009  7213 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "cordova.plugin.consent.Consent" on path: DexPathList[[zip file "/data/app/xxxx-Rr5Hk-hkzsdrSLT7eO9sjw==/base.apk"],nativeLibraryDirectories=[/data/app/xxxx-Rr5Hk-hkzsdrSLT7eO9sjw==/lib/arm, /data/app/xxxx-Rr5Hk-hkzsdrSLT7eO9sjw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
08-25 16:00:04.029  7009  7213 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08-25 16:00:04.030  7009  7213 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-25 16:00:04.030  7009  7213 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-25 16:00:04.030  7009  7213 W System.err: 	... 12 more
08-25 16:00:04.030  7009  7213 I System.out: Error adding plugin cordova.plugin.consent.Consent.
08-25 16:00:04.030  7009  7213 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
08-25 16:00:04.030  7009  7213 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
08-25 16:00:04.030  7009  7213 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
08-25 16:00:04.031  7009  7213 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
08-25 16:00:04.031  7009  7213 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
08-25 16:00:04.031  7009  7213 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
08-25 16:00:04.031  7009  7213 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:325)
08-25 16:00:04.031  7009  7213 W System.err: 	at android.os.Looper.loop(Looper.java:142)
08-25 16:00:04.031  7009  7213 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

### Reproducible Demo

Ionic 4 Cordova project with admob-plus and consent plugin.

**Comment by alexp25** [comment] 2020-08-26 08:00
Can we show custom consent window though (is it allowed)?

**Comment by rastafan** [comment] 2020-09-23 08:16
This is caused by the same issue found here: #144 
Manually copy the .java file in the correct path as specified in the issue, and it will start to work.

**Comment by rastafan** [comment] 2020-09-23 08:20
Actually, the relative pull request #180 has been merged 11 days ago, so you should be able to get the file to be copied automatically now. Just remove and re-add the plugin, then try again.

**Closed** 2021-01-10 05:16 UTC
Labels: wontfix
